// action types
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_SUMMARY = "UPDATE_SUMMARY";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const UPDATE_LOGINSTATUS = "UPDATE_LOGINSTATUS";

