export const UPDATE_SERVER_STATUS = 'UPDATE_SERVER_STATUS';
export const UPDATE_TOKEN_REGISTERED = 'UPDATE_TOKEN_REGISTERED';
export const RESET_CONTEXT = 'RESET_CONTEXT';
export const UPDATE_USER = 'UPDATE_USER';

export const GET_PERSISTED_CONTEXT = 'GET_PERSISTED_CONTEXT';

export const updateProps = {
  ABOVE_TAB_BAR: 'UPDATE_PROPS_ABOVE_TAB_BAR'
};

export const location = {
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  UPDATE_GPS_ADDRESS: 'UPDATE_GPS_ADDRESS',
  UPDATE_ADDRESSES: 'UPDATE_ADDRESSES',
  ADD_ADDRESS: 'ADD_ADDRESS',
  SELECT_CURRENT_DELIVERY: 'SELECT_CURRENT_DELIVERY'
};
