export const UPDATE_SERVER_STATUS = 'UPDATE_SERVER_STATUS'
export const UPDATE_TOKEN_REGISTERED = 'UPDATE_TOKEN_REGISTERED'
export const RESET_CONTEXT = 'RESET_CONTEXT'
export const GET_PERSISTED_CONTEXT = 'GET_PERSISTED_CONTEXT'
